# Generated by Django 5.2.6 on 2025-11-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="image_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Изображение (URL)"
            ),
        ),
        migrations.AlterField(
            model_name="flower",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="flowers/",
                verbose_name="Изображение (файл)",
            ),
        ),
    ]
